---
# sudo sed -i "s|%sudo\tALL=(ALL:ALL).*|%sudo\tALL=(ALL:ALL) NOPASSWD: ALL|g' /etc/sudoers
- name: "Allow sudo without password"
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    regexp: '^%sudo.*ALL=(ALL:ALL)'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'

# sudo sed -i '1 aauth sufficient pam_succeed_if.so user ingroup sudo\n' /etc/pam.d/common-auth
- name: "Disable password promts in gui"
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/common-auth"
    line: 'auth sufficient pam_succeed_if.so user ingroup sudo'
    insertafter: 'BOF'

- name: "Configure autologin"
  ansible.builtin.lineinfile:
    path: "/etc/lightdm/lightdm.conf"
    regexp: '^#?autologin-user=.*'
    line: 'autologin-user=kali'
